### ISSUE TITLE
How to prevent stacked observed holidays

### ISSUE THREAD

**Issue by kyrofa** [holidays/holidays#395]
This is more of a question than a bug report, I hope that's okay (feel free to direct me elsewhere if necessary).

I'm using this excellent gem to help with tracking holidays and PTO at work, and I'm struggling with groups of potentially observed holidays. Take Christmas, for example. At work, we get Christmas Eve, Christmas Day, and the day after Christmas off. I naively threw this together, then:

```
# [...]
months:
# [...]
  12:
  - name: Christmas Eve
    regions: [work]
    mday: 24
    observed: to_weekday_if_weekend(date)
  - name: Christmas Day
    regions: [work]
    mday: 25
    observed: to_weekday_if_weekend(date)
  - name: Day after Christmas
    regions: [work]
    mday: 26
    observed: to_weekday_if_weekend(date)
# [...]
```

That's not quite what I want, though. Say Christmas Day fell on a Sunday, like it does this year. That ^ logic would have Christmas Day (observed) and Day after Christmas (observed) land on the same day, the 26th. I'd like it to push Christmas Day (observed) to Monday, but Day after Christmas (observed) to Tuesday. How would I best go about something like this?
